### ISSUE TITLE
Trivia: Come decidere il punteggio?

### ISSUE THREAD

**Issue by Steffo99** [Steffo99/royalpack#4]
Possibilità:

- Risposte giuste
- Rapporto giuste/sbagliate
- Risposte giuste * Rapporto giuste/sbagliate
- ???

**Comment by Alby1** [comment]
giuste-sbagliate

**Comment by Steffo99** [comment]
https://gist.github.com/Steffo99/3e95caa7bfd08ab1512a49d515ef13b1

vado con `accuracy_bonus`
